### ISSUE TITLE
Text unreadable in MacOS Dark Mode

### ISSUE THREAD

**Issue by G4Hu** [angryip/ipscan#241] opened 2020-05-17 21:00 UTC
After updating to 3.7.0 on MacOS 10.14.6 with Dark Mode enabled, text in the app becomes unreadable because the text colors do not adjust to Dark Mode.

1. Update from 3.6.x to 3.7.0 on MacOS 10.14.6 (I can only test this version).
2. Open Angry Ip Scanner
3. Text in the Toolbar, Preferences and in the Thread window do not adjust to the Dark Mode color scheme of MacOS.

I expected the app to be instantly readable, it seems to take some time to adjust, but it does not always adjust.

**Screenshots**
<img width="816" alt="Angry IP Scanner bug Dark Mode" src="https://user-images.githubusercontent.com/8537915/82159921-11d46200-9892-11ea-9aa7-c705e9f37e8f.png">

**Versions:**
 - OS type and version: MacOS 10.14.6
 - java version "1.8.0_181"
   Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
   Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
 - Angry IP Scanner: 3.7.0

**Comment by angryziber** [comment] 2020-05-17 21:14
Duplicate of #231 
Please check version 3.7.1 with a fix

**Closed by angryziber** 2020-05-17 21:14 UTC

**Comment by G4Hu** [comment] 2020-05-17 22:26
Sorry, did not thoroughly check for existing issues. Thanks for the quick reply!
