### ISSUE TITLE
Version 3.7.3 reporting hosts that aren't there

### ISSUE THREAD

**Issue by Steffen75** [angryip/ipscan#269] opened 2020-11-10 14:38 UTC
OS: macOS 10.13.6
JRE: Oracle 1.8.0 271

I've just upgraded to 3.7.3 and this version reports ghost hosts that clearly aren't there. The ghosts got a blue button before their IP address, a ping time that is 0 ms and in very few cases also 1 ms and the rest of my selected columns (Hostname, MAC address, MAC manufacturer Web) all say [n/a].

The strange thing is that these ghosts aren't the exception. They are the norm. In my IPv4 /24 there are about 20 living hosts. Of the remaining IPs about 200 are incorrectly reported as ghosts and the rest of about 30 IPs are correctly reported as not being there.

Version 3.7.2 was working fine.

**Comment by campbellpj** [comment] 2020-12-18 00:55
I didn't have 3.7.2, but I get a similar result in 3.7.3 on Mac OS Catalina, showing 
25.56.207.81         MAC address 7A:79:19:38:CF:51
which is located in London (I am in Wisconsin). I get it again after resetting router to factory specs.

The router does not show it in its own survey. 

However, IPScan shows it too, as a "local user."

So is it really a ghost???

Can anyone explain this? If so, I would appreciate an email to campbell@beloit.edu

Thanks,

Paul Campbell, Math & CS, Beloit College, Wisconsin

**Comment by angryziber** [comment] 2021-01-18 18:35
@campbellpj which IP range are you scanning? IPs starting with 25 are not usually assigned to local networks...

For anyone else having similar problems: it is important to know which Pinger do you have selected Preferences.
Version 3.7.3 had the defaults for macOS changed from TCP/UDP to Java pinger due to issue #260 

Please try different available pingers and report the results. I personally cannot reproduce any problems with either of them.

**Comment by campbellpj** [comment] 2021-01-18 21:13
> On Jan 18, 2021, at 12:35 PM, Anton Keks <notifications@github.com> wrote:
> 
> 
> @campbellpj <https://github.com/campbellpj> which IP range are you scanning? IPs starting with 25 are not usually assigned to local networks...
> 

I scanned just 25.56.207.81 with Angry IP Scanner because that IP number showed up when I ran the program IP Scanner 3.99 (standard version). Today that program displays  25.56.207.81 at first but then deletes the listing before final report! The report shows 8 devices (all on my LAN) but says it found 10. Curiously, the FAQ for IP Scanner says "IP Scanner cannot find devices that are on different subnets. This means that if IP Scanner is running on a machine that has the IP number 192.168.1.2, it cannot find devices that have, for example, IP numbers like 10.0.1.2."
I have not yet  tried to contact support for IP Scanner:  usersupport@10base-t.com. <mailto:usersupport@10base-t.com>For anyone else having similar problems: it is important to know which Pinger do you have selected Preferences.
> Version 3.7.3 had the defaults for macOS changed from TCP/UDP to Java pinger due to issue #260 <https://github.com/angryip/ipscan/issues/260>
> 

I have been using that default Pinger:  Java Built-in

However, the site 25.56.207.81 appears as live, with a blue indicator, except when I use Pinger UDP packet (get red indicator with that Pinger).
> Please try different available pingers and report the results. I personally cannot reproduce any problems with either of them.
> 

The reason that I am looking into this matter is that I am concerned because 
----I regularly get warnings from Sophos of malware coming in, but I cannot attribute the malware to any particular email or other source; and 
----despite my use of Sophos on all my devices, in the last three months my ISP has sent me half a dozen warnings: "A device using your network may be infected with malware.”

Thanks for your help—sorry to bother you earlier at what I did not know was your work address.

Best wishes,

Paul C



-------------
Paul J. Campbell
Mathematics and Computer Science
Beloit College
700 College St.
Beloit, WI  53511-5595
USA

really old archived Web page at
https://web.archive.org/web/20090221120714/http://cs.beloit.edu/campbell/ <https://web.archive.org/web/20090221120714/http://cs.beloit.edu/campbell/>

**Comment by Steffen75** [comment] 2021-01-19 07:42
> Please try different available pingers and report the results. I personally cannot reproduce any problems with either of them.

I have just tried it with 3.7.2 and 3.7.3 using both pingers of each version.

Version 3.7.2 produces no ghosts no matter if I choose Java or Combined UDP+TCP as pinger.
Version 3.7.3 works fine with Java as selected pinger. Combined UDP+TCP produces ghosts for me with 3.7.3.

**Comment by angryziber** [comment] 2021-01-19 20:59
@Steffen75 thanks, that is a very valuable information.
I have reverted changes made in 3.7.3 in TCPPinger.

But I still help to understand why macOS sometimes throws ConnectException in case of dead hosts.
Please download the latest development macOS build: https://github.com/angryip/ipscan/suites/1859928858/artifacts/36142861

Extract, go into `Angry IP Scanner.app/Contents/MacOS` using Terminal and run manually `./ipscan` there.
After that, please scan your LAN using TCP pinger (some alive and some dead hosts) and provide the log from the terminal.

**Comment by campbellpj** [comment] 2021-01-19 21:47
> On Jan 19, 2021, at 3:00 PM, Anton Keks <notifications@github.com> wrote:
> 
> 
> @Steffen75 <https://github.com/Steffen75> thanks, that is a very valuable information.
> I have reverted changes made in 3.7.3 in TCPPinger.
> 
> But I still help to understand why macOS sometimes throws ConnectException in case of dead hosts.
> Please download the latest development macOS build: https://github.com/angryip/ipscan/suites/1859928858/artifacts/36142861 <https://github.com/angryip/ipscan/suites/1859928858/artifacts/36142861>
> 

I get a 404 at that address.

**Comment by angryziber** [comment] 2021-01-20 20:57
Very weird. I guess you can see the build itself here: https://github.com/angryip/ipscan/actions/runs/496975420
I have uploaded the same build here: https://we.tl/t-Xt5rXqgufL

**Comment by Steffen75** [comment] 2021-01-21 13:19
> Extract, go into `Angry IP Scanner.app/Contents/MacOS` using Terminal and run manually `./ipscan` there.
> After that, please scan your LAN using TCP pinger (some alive and some dead hosts) and provide the log from the terminal.

Done that. This build shows no ghosts for me. What I can't see in the terminal are hosts that have a web server listening.

Jan 21, 2021 2:07:43 PM net.azib.ipscan.core.net.TCPPinger ping
INFORMATION: /192.168.123.3: java.net.ConnectException: Connection refused (Connection refused)
Jan 21, 2021 2:07:43 PM net.azib.ipscan.core.net.TCPPinger ping
INFORMATION: /192.168.123.3: java.net.ConnectException: Connection refused (Connection refused)
Jan 21, 2021 2:07:43 PM net.azib.ipscan.core.net.TCPPinger ping
INFORMATION: /192.168.123.3: java.net.ConnectException: Connection refused (Connection refused)
Jan 21, 2021 2:07:44 PM net.azib.ipscan.core.net.TCPPinger ping
INFORMATION: /192.168.123.20: java.net.ConnectException: Connection refused (Connection refused)
Jan 21, 2021 2:07:44 PM net.azib.ipscan.core.net.TCPPinger ping
INFORMATION: /192.168.123.20: java.net.ConnectException: Connection refused (Connection refused)
Jan 21, 2021 2:07:44 PM net.azib.ipscan.core.net.TCPPinger ping
INFORMATION: /192.168.123.20: java.net.ConnectException: Connection refused (Connection refused)
Jan 21, 2021 2:07:47 PM net.azib.ipscan.core.net.TCPPinger ping
INFORMATION: /192.168.123.4: java.net.ConnectException: No route to host (connect failed)
Jan 21, 2021 2:07:47 PM net.azib.ipscan.core.net.TCPPinger ping
INFORMATION: /192.168.123.5: java.net.ConnectException: No route to host (connect failed)
Jan 21, 2021 2:07:47 PM net.azib.ipscan.core.net.TCPPinger ping
INFORMATION: /192.168.123.6: java.net.ConnectException: No route to host (connect failed)
Jan 21, 2021 2:07:47 PM net.azib.ipscan.core.net.TCPPinger ping
INFORMATION: /192.168.123.7: java.net.ConnectException: No route to host (connect failed)
Jan 21, 2021 2:07:47 PM net.azib.ipscan.core.net.TCPPinger ping
INFORMATION: /192.168.123.8: java.net.ConnectException: No route to host (connect failed)
Jan 21, 2021 2:07:47 PM net.azib.ipscan.core.net.TCPPinger ping
INFORMATION: /192.168.123.9: java.net.ConnectException: No route to host (connect failed)
Jan 21, 2021 2:07:47 PM net.azib.ipscan.core.net.TCPPinger ping

**Closed** 2021-01-22 16:25 UTC
