### ISSUE TITLE
java.lang.NoSuchMethodError: magnifyProc

### ISSUE THREAD

**Issue by cglmrfreeman** [angryip/ipscan#229] opened 2020-03-15 01:43 UTC
Trying to run the RPM or JAR of version 3.7.0 throws this error.

I am running OpenSUSE Tumbleweed Kernel 5.5.7-1-default x64 with openjdk 11.0.6. Full error below:

`java.lang.NoSuchMethodError: magnifyProc
        at org.eclipse.swt.internal.Callback.bind(Native Method)
        at org.eclipse.swt.internal.Callback.<init>(Callback.java:232)
        at org.eclipse.swt.widgets.Control.<clinit>(Control.java:100)
        at net.azib.ipscan.config.ComponentRegistry.mainShell(ComponentRegistry.java:41)
        at net.azib.ipscan.config.ComponentRegistry_MainShellFactory.proxyMainShell(ComponentRegistry_MainShellFactory.java:30)
        at net.azib.ipscan.config.ComponentRegistry_MainShellFactory.provideInstance(ComponentRegistry_MainShellFactory.java:21)
        at net.azib.ipscan.config.ComponentRegistry_MainShellFactory.get(ComponentRegistry_MainShellFactory.java:17)
        at net.azib.ipscan.config.ComponentRegistry_MainShellFactory.get(ComponentRegistry_MainShellFactory.java:8)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at net.azib.ipscan.config.DaggerMainComponent.createMainWindow(DaggerMainComponent.java:733)
        at net.azib.ipscan.gui.GUI.showMainWindow(GUI.java:46)
        at net.azib.ipscan.Main.main(Main.java:58)
Exception in thread "main" java.lang.NullPointerException
        at net.azib.ipscan.gui.GUI.showMessage(GUI.java:85)
        at net.azib.ipscan.Main.handleFatalError(Main.java:82)
        at net.azib.ipscan.Main.main(Main.java:74)
`
If anything else is required please let me know.

**Comment by Illuminaris1968** [comment] 2020-03-15 07:58
I have the exact same problem

java.lang.NoSuchMethodError: magnifyProc
        at org.eclipse.swt.internal.Callback.bind(Native Method)
        at org.eclipse.swt.internal.Callback.<init>(Callback.java:232)
        at org.eclipse.swt.widgets.Control.<clinit>(Control.java:100)
        at net.azib.ipscan.config.ComponentRegistry.mainShell(ComponentRegistry.java:41)
        at net.azib.ipscan.config.ComponentRegistry_MainShellFactory.proxyMainShell(ComponentRegistry_MainShellFactory.java:30)
        at net.azib.ipscan.config.ComponentRegistry_MainShellFactory.provideInstance(ComponentRegistry_MainShellFactory.java:21)
        at net.azib.ipscan.config.ComponentRegistry_MainShellFactory.get(ComponentRegistry_MainShellFactory.java:17)
        at net.azib.ipscan.config.ComponentRegistry_MainShellFactory.get(ComponentRegistry_MainShellFactory.java:8)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at net.azib.ipscan.config.DaggerMainComponent.createMainWindow(DaggerMainComponent.java:733)
        at net.azib.ipscan.gui.GUI.showMainWindow(GUI.java:46)
        at net.azib.ipscan.Main.main(Main.java:58)
Exception in thread "main" java.lang.NullPointerException
        at net.azib.ipscan.gui.GUI.showMessage(GUI.java:85)
        at net.azib.ipscan.Main.handleFatalError(Main.java:82)
        at net.azib.ipscan.Main.main(Main.java:74)

Downloaded the .jar file and get 

Error: Could not find or load main class ipscan-any-3.7.0.jar
Caused by: java.lang.ClassNotFoundException: ipscan-any-3.7.0.jar

When running  "sudo java ipscan-any-3.7.0.jar"

Running the program from xwindows (dont remember what it is called i get a message saying.

g_signal_handler

**Comment by conraid** [comment] 2020-03-16 09:12
Same here
```
java.lang.NoSuchMethodError: magnifyProc
        at org.eclipse.swt.internal.Callback.bind(Native Method)
        at org.eclipse.swt.internal.Callback.<init>(Callback.java:232)
        at org.eclipse.swt.widgets.Control.<clinit>(Control.java:100)
        at net.azib.ipscan.config.ComponentRegistry.mainShell(ComponentRegistry.java:41)
        at net.azib.ipscan.config.ComponentRegistry_MainShellFactory.proxyMainShell(ComponentRegistry_MainShellFactory.java:30)
        at net.azib.ipscan.config.ComponentRegistry_MainShellFactory.provideInstance(ComponentRegistry_MainShellFactory.java:21)
        at net.azib.ipscan.config.ComponentRegistry_MainShellFactory.get(ComponentRegistry_MainShellFactory.java:17)
        at net.azib.ipscan.config.ComponentRegistry_MainShellFactory.get(ComponentRegistry_MainShellFactory.java:8)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at net.azib.ipscan.config.DaggerMainComponent.createMainWindow(DaggerMainComponent.java:733)
        at net.azib.ipscan.gui.GUI.showMainWindow(GUI.java:46)
        at net.azib.ipscan.Main.main(Main.java:58)
Exception in thread "main" java.lang.NullPointerException
        at net.azib.ipscan.gui.GUI.showMessage(GUI.java:85)
        at net.azib.ipscan.Main.handleFatalError(Main.java:82)
        at net.azib.ipscan.Main.main(Main.java:74)

```

with Slackware Current
kernel 5.4.25
jdk 13.0.2

**Comment by angryziber** [comment] 2020-03-16 09:17
Thanks for reporting. All Linux 64 builds have been fixed now, please download again

**Closed by angryziber** 2020-03-16 09:17 UTC

**Comment by angryziber** [comment] 2020-03-16 09:19
@Illuminaris1968 requires libswt packages to be installed on the system.
Which distribution do you use?

**Comment by conraid** [comment] 2020-03-16 09:21
Yes, now work fine. Thanks

**Comment by nu11ptr** [comment] 2021-08-21 14:38
@angryziber Could I inquire what the fix was? I have my own SWT app I'm compiling with 'native-image' and getting this same error. I can't seem to figure out what the issue is, thx!
