### ISSUE TITLE
Compatibility with AdoptJDK Java disrtibution?

### ISSUE THREAD

**Issue by tKoudy** [angryip/ipscan#187] opened 2019-05-03 08:31 UTC
Hello,
is Angry IP Scanner compatible with AdoptJDK Java distribution, please?
On Win 10 x64 I have installed OpenJDK8U-jre_x64_windows_hotspot_8u212b03.msi from adoptopenjdk.net, but I'm getting error "This application requires a Java Runtime Environment 1.7.0" when I try to run portable version of Angry IP Scanner (tried both, x32 and x64).

Thanks in advance for any comment.
Tomas

**Comment by jendib** [comment] 2019-07-12 19:20
It's actually an issue with launch4j and not AngryIP.
To bypass the problem I created a .reg file with this content (please change the path to match your configuration) and then open it to write to the registry.
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft]

[HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\JDK]
"CurrentVersion"="11.0.3.7-ojdkbuild"

[HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\JDK\11]
"JavaHome"="C:\\Program Files\\AdoptOpenJDK\\jdk-11.0.3.7-hotspot"
```

**Comment by angryziber** [comment] 2019-07-16 19:50
Another option would be to run `path\to\javaw -jar ipscan.exe`, then Launch4J will not try to search for JRE

**Comment by angryziber** [comment] 2019-07-24 21:51
Duplicate of https://github.com/angryip/ipscan/issues/179

**Closed by angryziber** 2019-07-24 21:51 UTC
